# Scipy Graph 
*working with graph*
* Graph are an essential data structure
* Scipy Provide us with the module *scipy.sparse.csgraph* for working with such data structure
# Adjacency matrix 
* Adjacency matrix is a nxn matrix where n is the number of element in the garph
and the value represented the connection b/w the element
# Connected Components
* Find all of the connected components with the *connected.components()* method

In [1]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
arr = np.array([[1,2,3],[5,6,7],[4,5,3]])
newarr = csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0]))


# Dijksrta 
* use the dijkstra method to find the sortest path in the graph from one element to another
1  *return-predecessors:* Boolean (true the return whole path of traversal otherwise false)

2 - *Indices* : index of the element to return all the paths from that element only

2 - *limit* : max weight of path

In [2]:
# Find the sortest path from element 1 to 2
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
arr = np.array([[0,1,2],
                [1,0,0],
                [2,0,0]])
newarr = csr_matrix(arr)
print(dijkstra(newarr,return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


# Floyd Warshall 
* Use the floyd_warshall() method to find the sortest path b/w all pair elements


In [3]:
# Find the sortest path b/w all pair of the element
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
arr = np.array([[0,1,2],[1,0,0],[2,0,0]])
newarr = csr_matrix(arr)
print(floyd_warshall(newarr,return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


# Bellman Ford
* The bellman_ford() method can also find the sortest path b/w all pair of the element,but this method can be handle negative weight as well.

In [5]:
# Find sortest path from element 1 to 2 with given garph with a negative weight
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix
arr = np.array([[0,-1,0],     # Negative weight is nesessary    
                [1,0,0],
                [2,0,0]])
newarr = csr_matrix(arr)
print(bellman_ford(newarr,return_predecessors=True))

(array([[ 0., -1., inf],
       [ 1.,  0., inf],
       [ 2.,  1.,  0.]]), array([[-9999,     0, -9999],
       [    1, -9999, -9999],
       [    2,     0, -9999]]))


# depth First order
* The *depth_first_order* method return a depth first traversal from a node
* This funtion is taking following steps

1 - the graph
2 - the starting element to traverse graph from

In [6]:
# Traverse the graph depth first for given adjacency matrix
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix
arr = np.array([[0,1,0,1],
                [1,1,1,1],
                [2,1,1,0],
                [0,1,0,1]])
newarr = csr_matrix(arr)
print(depth_first_order(newarr,1))

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


# breadth first Order
* The breadth_first_order() method returns a breadth first traversal from a node
* This function take following argument:

1 - Graph

2 - The starting element to traverse graph from


In [9]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix
arr = np.array([[0,1,0,1],
                [1,1,1,1],
                [2,1,1,0],
                [0,1,0,1]
            ])
newarr = csr_matrix(arr)
print(breadth_first_order(newarr,3))

(array([3, 1, 0, 2]), array([    1,     3,     1, -9999]))
