# Random Number in Numpy
*What Is Random Number*
* Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [2]:
# NumPy offers the random module to work with random numbers
# Generate Random Number from 0 to 100
from numpy import random
x = random.randint(100)
x 


41

In [3]:
# Generate Rondom Float
# The random module's rand() method returns a random float between 0 and 1
flo = random.rand()
flo


0.05362431302368431

Generate Random Array

In [13]:
# Generate random 1-D Array containing 5 random integer from 0 to 100
arr = random.randint(100,size=(10))  
arr

array([90, 82, 91, 78, 34, 18, 75, 84,  1, 58])

In [5]:
# Generate 2-D array with 3 rows 
arr2 = random.randint(100,size=(3,3))
arr2

array([[99, 59,  0],
       [52, 29, 85],
       [68, 69, 48]])

In [6]:
arr2 = random.randint(100,size=(3,3,3))
arr2

array([[[63, 48, 45],
        [75, 94, 57],
        [56, 79, 84]],

       [[31, 85,  1],
        [67, 71, 45],
        [53, 38,  2]],

       [[11, 89, 84],
        [68, 76, 16],
        [38, 93, 68]]])

The rand() method also allows you to specify the shape of the array.

In [7]:
ran = random.rand(5)
ran

array([0.68254191, 0.64781152, 0.64405572, 0.93718382, 0.02442751])

In [8]:
# Generate a 2-D array with 3 rows in float
arr = random.rand(3,3)
arr

array([[0.25789776, 0.41157447, 0.55205692],
       [0.87582786, 0.04160512, 0.84165   ],
       [0.10251457, 0.35559041, 0.11400623]])

# Generate Random Number From Array
* The choice() method allows you to generate a random value based on an array of values.

* The choice() method takes an array as a parameter and randomly returns one of the values.

In [9]:
cho = random.choice([1,3,4,5,6])
cho

4

In [10]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)
cho = random.choice([3,5,7,9],size=(3,5))
cho


array([[9, 5, 7, 9, 3],
       [9, 5, 5, 7, 7],
       [9, 5, 7, 7, 5]])

# Random permutations
*random permutation of element*
* A permutation refer to an arrangement of element e.g. [3,2,1] is a permutation of [1,2,3] and vice versa .
* The numpy Random mudule provide two methods for this : suffle() and permutation().
# Suffling array
* Shuffle means changing arrangement of element in-place .i.e in the array itself 

In [11]:
from numpy import random
import numpy as np
arr = np.array([3,4,5,3])
random.shuffle(arr)
print(arr)  # The suffle() methods makes change to the orignal array

[3 4 3 5]


*Generating Permutation of the array*
|

In [12]:
arr = np.array([4,5,7,5,4,3])
print(random.permutation(arr)) # It set the data in ASC order

[4 3 5 7 4 5]
