# *Why use numpy*   # Single star for italic 
* **numpy also provide efficient storage**  Duble star for bold 
* It also provides better ways to handing data for proccessing
* it is fast
* Numpy uses relatively less memory to store data

In [1]:
import numpy as np

In [67]:
arr = np.array([3,4,6,3,5],np.int32)
arr.dtype

dtype('int32')

In [68]:
arr[1]

4

In [4]:
arr.shape

(1, 5)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr[0,1] = 55        #Indexing and slicing

In [7]:
arr

array([[ 3, 55,  6,  3,  5]])

Array Creation :Conversion from other Python structure

In [8]:
listarray = np.array([[1,2,3],
                      [4,5,6],
                      [6,7,8]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
np.array({34,5,44})   #  set

array({34, 44, 5}, dtype=object)

In [69]:
zeros = np.zeros((2,4))

In [13]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
rng = np.arange(1,101)   # arange create data given criteria
rng

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
lspace = np.linspace(1,10,5)
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.39076198e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        1.37961302e-306, 1.42410974e-306, 2.22522596e-306]])

In [17]:
like = np.empty_like((lspace))
like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
ide = np.identity(40)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
ide.shape 

(40, 40)

In [20]:
arr = np.arange(99)  

In [21]:
arr       

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr = arr.reshape(3,33)


In [23]:
arr= arr.ravel()

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.shape

(99,)

In [26]:
x = [[2,3,4],[43,6,5],[3,5,3]]
ar = np.array(x)
ar

array([[ 2,  3,  4],
       [43,  6,  5],
       [ 3,  5,  3]])

In [27]:
ar.sum(axis=0)

array([48, 14, 12])

In [28]:
ar.sum(axis=1)

array([ 9, 54, 11])

In [29]:
ar.T    # transpose meaning that change the row into column and column in row


array([[ 2, 43,  3],
       [ 3,  6,  5],
       [ 4,  5,  3]])

In [30]:
ar.flat

In [31]:
for item in ar.flat:  # Itrate  on the element
    print(item)

2
3
4
43
6
5
3
5
3


In [70]:
ar.ndim  # For cheaking the Dimention of array 

2

In [71]:
# Join arrays of one dimentional array
arr4 = np.array([12,33,44,55])
arr5 = np.array([3,4,6,4])
arr = np.concatenate((arr4,arr5))
arr

array([12, 33, 44, 55,  3,  4,  6,  4])

In [72]:
# Join arrays od tow dimentional array
a = np.array([[1,2,4],[2,3,5]])
b = np.array([[2,3,5],[1,5,7]])
join = np.concatenate((a,b),axis=0)  # Axis 0 for Row and Axis 1 for column
join

array([[1, 2, 4],
       [2, 3, 5],
       [2, 3, 5],
       [1, 5, 7]])

In [73]:
# Join array with the help of stack funtions
arr2 = np.array([9,7,5])
arr1 = np.array([6,5,3])
res = np.stack((arr2,arr1),axis=1)   # Axis = 1 for vertex
res

array([[9, 6],
       [7, 5],
       [5, 3]])

In [36]:
# Stacking from row
# Numpy Provide a helper function : hstack to stack along Row
arr = np.hstack((arr2,arr1))
arr

array([9, 7, 5, 6, 5, 3])

In [37]:
# Stacking Along column 
# Numpy providea helper function : vstack() to stack from column
arr1 = np.array([1,3,5])
arr3 = np.array([4,5,3])
res = np.vstack((arr1,arr3))
res

array([[1, 3, 5],
       [4, 5, 3]])

In [38]:
# Stackin along Height(depth)
# Numpy Provide a helper function : dstack() to stack along height, which is a same as depth
arr = np.dstack((arr2,arr1))
arr

array([[[9, 1],
        [7, 3],
        [5, 5]]])

# Numpy splitting array
*Numpy Splitting array*
* Spiltting a reverse operation of joining
* Joining merge multiple array into one and splitting brack one array into multiple
* We Use array_split() For splitting array we pass it the array we want to split
and the number of split


In [39]:
# Split the array in 3 parts or more
arr = np.array([1,2,4,5,6,8])
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([4, 5]), array([6, 8])]

In [40]:
#If the array has less elements than required,
# it will adjust from the end accordingly.
newarr = np.array_split(arr,4)
newarr

[array([1, 2]), array([4, 5]), array([6]), array([8])]

# Split Into Arrays
The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [41]:
newarr = np.array_split(arr,3)
print([newarr[0]])
print([newarr[1]])
print([newarr[2]])

[array([1, 2])]
[array([4, 5])]
[array([6, 8])]


# Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [42]:
arr = np.array([[1,2,4],[3,5,7],[7,8,9],[7,6,5]])
newarr = np.array_split(arr,4)
newarr

[array([[1, 2, 4]]),
 array([[3, 5, 7]]),
 array([[7, 8, 9]]),
 array([[7, 6, 5]])]

In [43]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newarr = np.array_split(ar,3)
newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]])]

In [44]:
newarr = np.array_split(ar,3,axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15]])]

An alternate solution is using hsplit() opposite of hstack()

In [45]:
new = np.hsplit(ar,3)
new

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15]])]

In [46]:
newarr = np.hstack(ar)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

vstack ,dstack ,vsplit ,dsplit

# Numpy Search Array
*Searching array*
* You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [47]:
arr = np.array([1,2,3,4,5,6,7,4,6,4])   # Its finding only address of variable
x = np.where((arr == 4))   
x

(array([3, 7, 9], dtype=int64),)

In [48]:
# Find the index when value is eve
even = np.where(arr%2 == 0)   # For finding the index of odd number arr% == 1
even

(array([1, 3, 5, 7, 8, 9], dtype=int64),)

# Search Sorted
* There is a method called *searchsorted()* which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
* **The searchsorted() method is assumed to be used on sorted arrays.**

In [49]:
arr = np.array([4,5,6,7,8,9])
sort = np.searchsorted(arr ,7)   # Index Finding  address
sort


3

In [50]:
sort = np.searchsorted(arr,7,side='right') # side = 'right' or 'right' both are same
sort

4

# Finding Multiple Value from the list

In [51]:
data = np.searchsorted(arr,[4,5,7])
data

array([0, 1, 3], dtype=int64)

# Numpy Sorting Array
* Sorting means putting elements in an ordered sequence.

* Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
* The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [52]:
# Sorted the array
sort = np.sort(arr)
sort
# Note: This method returns a copy of the array, leaving the original array unchanged.

array([4, 5, 6, 7, 8, 9])

In [53]:
# Sorted the alphabetically
alpha = np.array(['banana','mango','woodapple','ledyfinger'])
final = np.sort(alpha)
final

array(['banana', 'ledyfinger', 'mango', 'woodapple'], dtype='<U10')

In [54]:
# Sorted a Boolean Array
arr = np.array([True,False,True])
bol = np.sort(arr)
bol

array([False,  True,  True])

* Sorting 2D Array


In [55]:
arr = np.array([[26,3,4],[4,10,8]])
data = np.sort(arr)
data

array([[ 3,  4, 26],
       [ 4,  8, 10]])

# Numpy Filter Array
* Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [56]:
# Create an array  from the element on index 0 and 2
arr = np.array([41,42,43,44])
newarr = [True,False,True,False]  # Where Ture then print otherwise not
new = arr[newarr]
new

array([41, 43])

In [57]:
arr = np.array([41, 42, 43, 44,55])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True, True]
[43 44 55]


In [58]:
arr = np.array([3,9,6,5,3,2])
fill = []
for data in arr:
    if data > 5:
        fill.append(True)
new = arr[fill]
print(new)
    

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 2