In [1]:
import numpy as np

In [2]:
# Create a ndarray with tuple
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Create a 3D array
arr = np.array([[[2,3,4],[2,3,4]],[[2,3,4],[3,3,2]]])
print(arr)
print(arr.ndim)

[[[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [3 3 2]]]
3


In [4]:
arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)
print("Number of dimentional:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimentional: 5


# Indexing 
*Accessing the data of list*

In [5]:
# 1D array
arr = np.array([1,2,3,4])
print(arr[2])

3


In [6]:
# Accessing data from 2D array
arr = np.array([[1,2,3,],
                [3,4,5]])
print(arr[0,2])

3


In [7]:
# Accessing data from 3D array
arr = np.array([[[2,3,4],
                 [3,3,2]],
                 [[2,3,4],
                  [3,4,4]]])
print(arr)
print(arr[0,1,1])

[[[2 3 4]
  [3 3 2]]

 [[2 3 4]
  [3 4 4]]]
3


# negative Indexing

In [8]:
arr = np.array([[1,2,3,4],
                [8,6,5,4]])
print(arr)
print(arr[0,-3])

[[1 2 3 4]
 [8 6 5 4]]
2


# Slicing 
*numpy array Slicing*

In [9]:
arr = np.array([2,3,4,5,6,7,7])
print(arr[1:6])

[3 4 5 6 7]


In [10]:
print(arr[4:])

[6 7 7]


In [11]:
# Negative Slicing
print(arr[-3:-1])

[6 7]


In [12]:
print(arr[::2])
print(arr)

[2 4 6 7]
[2 3 4 5 6 7 7]


*Slicing 2D array*

In [13]:
arr = np.array([[2,3,4,3,5],
                [3,4,5,5,6]])
print(arr)
print(arr[0, 0:4])

[[2 3 4 3 5]
 [3 4 5 5 6]]
[2 3 4 3]


In [15]:
# From both element return index 2:
arr = np.array([[1,3,5,3,6],
                [4,3,4,5,3]])
print(arr)
print(arr[0:2,1])

[[1 3 5 3 6]
 [4 3 4 5 3]]
[3 3]


In [19]:
# From both element slice index 1 to index 4(not include) this will return 2D array
arr = np.array([[1,2,3,4,5,6],[9,7,7,6,5,4]])
print(arr)
print(arr[0:2,1:4])

[[1 2 3 4 5 6]
 [9 7 7 6 5 4]]
[[2 3 4]
 [7 7 6]]


# Data type 
*Cheaking the data type of array*

In [22]:
arr = np.array([1,2,3,4,5])
arr2 = np.array(['name','ram','shyam'])

print(type(arr))
print(arr2.dtype)
print(arr.dtype)

<class 'numpy.ndarray'>
<U5
int32


*Creating array with define data type* 

In [24]:
arr = np.array([34,3,3,2,4,5],dtype='S')
print(arr)
print(arr.dtype)    
# For i,u ,f,s and U we can define size as well 

[b'34' b'3' b'3' b'2' b'4' b'5']
|S2


*create an array with datatype 4 bytes Integer*

In [27]:
arr = np.array([2,3,53,33,4],dtype='i4')
print(arr.dtype)

int32


# what a value can not be converted ?
* If a type given in which element can't be casting then Numpy will raise a valueError
Exp - A non Integer String like 'a' can't be converted to integer (will raise an Error):


In [29]:
arr = np.array([2,2,'a',5,3],dtype='i')  # can't be change
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

# Convert datatype in Exiting array 
* The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

* The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

* The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [32]:
# Change the datatype from float to integer by using 'i' as a parameter  value:
# Astype
arr = np.array([1.1,3.2,4.3])
newarr = arr.astype('i')
print(newarr)
print(arr.dtype)
print(newarr.dtype)

[1 3 4]
float64
int32


In [33]:
# Change the data from float to integer by using int parameter
newarr = arr.astype('int')
print(newarr.dtype)
# Similarly we can change float/int/char into bool or other datatype

int32


# Numpy array Copy and View
* Copy array copy the data of orignal array 
* if change in orignal will not affect copy or change copy data will not affect in orignal data
* View is use for showing the data from orignal data

# Copy

In [39]:
arr = np.array([3,4,5,2,5,6])
x  = arr.copy()
arr[0] = 43
print(x)
print(arr)

[3 4 5 2 5 6]
[43  4  5  2  5  6]


# View :

In [41]:
# Make a view,change the orignal array,and display both array
arr = np.array([3,4,6,4,3])
x = arr.view()
arr[0] = 34
print(x)
print(arr)   # The view should be affected by the change made to the orignal array


[34  4  6  4  3]
[34  4  6  4  3]


*Cheak if array owns its data*

In [45]:
# Print the value of the base attribute to cheak if an array owns its data or not
arr = np.array([2,4,2,4,2])
y = arr.copy()
x = arr.view()
print(x.base)
print(y.base)


[2 4 2 4 2]
None


*Numpy array shape*

In [48]:
# Cheak the shape of array with the shape attribute
arr = np.array([[4,3,3,5,3],
                [4,3,4,3,2]])
print(arr.shape)

(2, 5)


In [52]:
# Create an array of 5 dimention using ndim using a vector with value 1,2,3,4
# and verify the last dimention value 4
arr =np.array([1,2,3,4],ndmin=5)
print(arr)  
print('shape of array:',arr.shape)    

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


# Numpy array Reshaping 
* reshape mean change the shape of array
* the shape of array  is the number of element in each dimention.
* by reshaping we can add or remove dimensions or change number of element in each dimention 

In [57]:
# Reshape from 1D to 2D 
arr = np.array([3,4,5,4,3,5,6,7,6,10,11,12])
new = arr.reshape(4,3)
print(new)

[[ 3  4  5]
 [ 4  3  5]
 [ 6  7  6]
 [10 11 12]]


In [69]:
# Reshape from 1D to 3D array
arr = np.array([1,2,3,4,5,6,6,7,8,9,10,11])
new = arr.reshape(2,3,2)
print(new)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [67]:
arr = np.array([[[2,3,4],[3,4,5]],[[3,3,3],[2,3,4]]])
print(arr)   # 3D Array

[[[2 3 4]
  [3 4 5]]

 [[3 3 3]
  [2 3 4]]]


*return copy or view*

In [70]:
# cheak the return a copy or a view
print(arr.reshape(2,3,2).base)

[ 1  2  3  4  5  6  6  7  8  9 10 11]


*Unknown Dimention*
* You are allowed to have one "unknown" dimension.
* Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
* Pass -1 as the value, and NumPy will calculate this number for you.

In [74]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


*Flattening the array*
* Flattening array meaning convert a multidimentional array into 1D array
* We can use reshape(-1)to do this

In [75]:
# Convert the array into 1D array
arr = np.array([[1,2,4],[3,4,5]])
new = arr.reshape(-1)
print(new)

# there have a lot of changing the shape of array in numpy flatten,ravel and also
# rearranging  the element rot90,flip,fliplr,flipud etc ,these fall under intermediate
# to advance section of numpy

[1 2 4 3 4 5]


# Itrating Array
* Itrating meaning going through element one by one
* As we deal with multi dimentional array in numpy ,we can do this using besic for loop in python
* If we iterate on a 1-D array it will go through each element one by one.




In [77]:
arr = np.array([2,4,2,1,5,3])
for i in arr:
    print(i)

2
4
2
1
5
3


In [79]:
# 2D Array
arr = np.array([[4,3,2],[3,4,5]])
for x in arr:
    print(x)

[4 3 2]
[3 4 5]


In [81]:
# Iterate  on each scalar element of the 2D array
arr = np.array([[2,3,2],[4,3,2]])
for x in arr:
    for y in x:
        print(y)    

2
3
2
4
3
2


*Iterating 3-D Array*
* In a 3-D array it will go through all the 2-D array

In [83]:
arr = np.array([[[2,3,4],[3,4,5]],[[3,4,3],[3,4,5]]])
for x in arr:
    print(x)

[[2 3 4]
 [3 4 5]]
[[3 4 3]
 [3 4 5]]


*Iterate Down to the Scalars*

In [86]:
for i in arr:
    for j in i:
        for z in j:
            print(z)

2
3
4
3
4
5
3
4
3
3
4
5


# iterating array using nditer()
* The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration

In [89]:
arr =  np.array([[[1,2,3],[5,4,3]],[[3,4,4],[6,6,5]]])

for i in np.nditer(arr):
    print(i)

1
2
3
5
4
3
3
4
4
6
6
5


# Itrating array with diffent datatype
* op_dtypes 
* flag = ['buffered']

In [90]:
arr = np.array([3,4,5,4,6])
for x in np.nditer(arr,flags=['buffered'],op_dtypes='S'):
    print(x)

b'3'
b'4'
b'5'
b'4'
b'6'


In [107]:
arr = np.array([[2,3,4],
                [6,5,6]])
for i in np.nditer(arr[:,:2]):
    print(i)

2
3
6
5


*Inumerated Iteration using ndenumerate()*

In [109]:
arr = np.array([4,4,4])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 4
(1,) 4
(2,) 4


*Enumerate on following 2D array's elements:*

In [111]:
arr = np.array([[3,4,6],
                [4,3,3]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 3
(0, 1) 4
(0, 2) 6
(1, 0) 4
(1, 1) 3
(1, 2) 3


In [113]:
# 3D Array
arr = np.array([[[3,3,3],
                 [5,5,5]],
                 [[2,3,5],
                  [6,6,5]]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0, 0) 3
(0, 0, 1) 3
(0, 0, 2) 3
(0, 1, 0) 5
(0, 1, 1) 5
(0, 1, 2) 5
(1, 0, 0) 2
(1, 0, 1) 3
(1, 0, 2) 5
(1, 1, 0) 6
(1, 1, 1) 6
(1, 1, 2) 5


# Joining Numpy array

* joining means putting contents of two or more array in single array
* In sql we join table base on the key ,whereas in numpy we join array by axis
* We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0. 

In [116]:
arr1 = np.array([3,4,2,4,5])
arr2 = np.array([5,3,4,5,5])    
sum = np.concatenate((arr1,arr2))
print(sum)

[3 4 2 4 5 5 3 4 5 5]


*Join 2D array along rows (axis=1)*

In [119]:
arr1 = np.array([[3,3,4],
                 [5,3,2]])
arr2 = np.array([[6,7,8],
                 [9,7,6]])
con = np.concatenate((arr1,arr2),axis=0)  # axis = 0 means horizontal 
print(con)                                # axis = 1 mean  vertical

[[3 3 4]
 [5 3 2]
 [6 7 8]
 [9 7 6]]


*Joining array using stack fucntion*


In [122]:
sum = np.stack((arr1,arr2),axis=1)
print(sum)

[[[3 3 4]
  [6 7 8]]

 [[5 3 2]
  [9 7 6]]]
